plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.expensebuttontracker'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.expensebuttontracker'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '2.1.0'
    }

    flavorDimensions 'distribution'
    productFlavors {
        upgrade {
            dimension 'distribution'
            manifestPlaceholders = [appLabel: 'ManageMe', importEnabled: 'false']
        }
        migration {
            dimension 'distribution'
            applicationIdSuffix '.synced'
            versionNameSuffix '-migration'
            manifestPlaceholders = [appLabel: 'ManageMe Sync', importEnabled: 'true']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
